server:
    port: 8080

spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/peoples
      username: postgres
      password: postgres

    jpa:
      hibernate:
        ddl-auto: create